### ISSUE TITLE
The DDD recommendation is to implement...

### ISSUE THREAD

**Issue by darkspock** [cqrs-by-example/book-issues#10]
"The DDD recommendation is to implement each Bounded Context as a separate application that
will interact with the others via API calls or a messaging system."
Not sure about this recommendation. I can't remember it.

**Comment by keyvanakbary** [comment]
DDD is not defined by us, the book covers CQRS and makes a brief summary on what DDD is. We recommend about reading DDD before (in our previous book, or the Blue [Eric Evans] or Red [Vaughn Vernon] books). In DDD, the recommendation is to implement each Bounded Context as ...

Thanks!
