### ISSUE TITLE
Repository inside DomainModel

### ISSUE THREAD

**Issue by darkspock** [cqrs-by-example/book-issues#11]
In the text  The DomainModel will contain the Domain concepts such as the Author and Cheep Aggregates or the AuthorRepository and CheepRepository Repositories."

I think is Repositories Interfaces.

**Comment by keyvanakbary** [comment]
A Repository is a high-level DDD concept, them being interfaces is implicit. Otherwise we would have wrote something like `DoctrineCheepRepository` in Infrastructure.

Thanks for your contribution anyway!
