### ISSUE TITLE
Some small typos

### ISSUE THREAD

**Issue by phpfour** [cqrs-by-example/book-issues#2]
## 1. Preface (ii)

![image](https://user-images.githubusercontent.com/171715/83559606-a8fa1480-a536-11ea-9716-85bb1b0fee43.png)

## 2. Acknowledgements 

![image](https://user-images.githubusercontent.com/171715/83558718-40f6fe80-a535-11ea-82d0-2b3dca7274e7.png)

## 3. A Journey Towards CQRS (page 7)

![image](https://user-images.githubusercontent.com/171715/83559392-53256c80-a536-11ea-8a39-feb34bee125d.png)

**Comment by carlosbuenosvinos** [comment]
Thanks for reporting your issue! It's fixed now and a new book version is ready. You are now part of the contributors!

![image](https://user-images.githubusercontent.com/351553/83635222-26a83980-a5a4-11ea-8a5b-1e6cc348d01c.png)

**Comment by phpfour** [comment]
@carlosbuenosvinos It's my pleasure, glad to help out!
