### ISSUE TITLE
Incorrect reference to example implementation

### ISSUE THREAD

**Issue by phpfour** [cqrs-by-example/book-issues#3]
Hi @carlosbuenosvinos

I think there is an incorrect reference to an example implementation in the `The Command Side` section of the **Anatomy of CQRS** chapter. The example implementation has only one named constructor:

![image](https://user-images.githubusercontent.com/171715/84556960-88a53380-ad48-11ea-8156-e8f6d849c120.png)

...whereas two different named constructors are being referenced in the following paragraphs:

![image](https://user-images.githubusercontent.com/171715/84556976-cdc96580-ad48-11ea-8d1d-074436c73709.png)

Thanks!

**Comment by carlosbuenosvinos** [comment]
I'll take a look to it. Thanks!

**Comment by carlosbuenosvinos** [comment]
References do not exist anymore.
