### ISSUE TITLE
Unable to access example code

### ISSUE THREAD

**Issue by ashishkpoudel** [cqrs-by-example/book-issues#4]
The link (https://github.com/cqrs-by-example/cheeper) for code example pointed in book does not exists.

**Comment by carlosbuenosvinos** [comment]
It's still in private mode. We are creating a slack channel and we will invite all the people that is buying the book. For now, you can access by joining this link: https://join.slack.com/t/cqrs-by-example-book/shared_invite/zt-g5citbqv-T_D_peP2wLgdiXTzOqUovQ
