### ISSUE TITLE
Word duplicated

### ISSUE THREAD

**Issue by proyectotau** [cqrs-by-example/book-issues#6]
Last paragraph of _Other CQRS Components_ section, just before of _Two Sides Of The Same Coin_ section, **affected** is duplicated.

It says:
`Behind the scenes, the Domain Events, triggered by Command Handlers and **affected** Entities **affected**, will be handled by one or multiple Projectors or Process Managers that will generate the read models optimized for the Query Side. Query requests will simply go and fetch the data ready to be presented to customers.`

**Comment by carlosbuenosvinos** [comment]
Fixed, thanks! It will be included in the next release
